version: '3'

services:

  mysql:
    image: arm64v8/mysql
    env_file:
      - .env.mysql
    ports:
      - "3306:3306"

  production:
    hostname: mydocker
    build: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    command: npm run start
    depends_on:
      - mysql

  development:
    hostname: mydocker
    build: .
    ports:
      - "1337:1337"
    environment:
      - PORT=1337
    env_file:
      - .env.mysql
    user: node
    command: npm run develop
    depends_on:
      - mysql
